### ISSUE TITLE
Any chance to get support for Linux?

### ISSUE THREAD

**Issue by maxime1992** [FL33TW00D/whisper-turbo#30]
Hello,

this is a really cool project. I wanted to try it out but when the base model loads and reaches 100% I get this error:

![image](https://github.com/FL33TW00D/whisper-turbo/assets/4950209/207ab201-667e-4b94-ab32-f506a22290a9)

I was about to make a report bug then saw in the bug report than only mac and windows are supported so maybe that's expected.

Are you planning on adding Linux support at some point?

Thanks!

**Comment by FL33TW00D** [comment]
Hey @maxime1992,
Linux support is currently behind a flag, you’ll need to start chrome with the flags provided here: https://github.com/gpuweb/gpuweb/wiki/Implementation-Status

Please let me know if it works I haven’t got a Linux machine to test on

**Comment by maxime1992** [comment]
Thanks!

Tried it on Firefox nightly as explained [here](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status#firefox)

![image](https://github.com/FL33TW00D/whisper-turbo/assets/4950209/47d57ddd-1acd-4336-a325-1d46029b5b8c)

Once the model is done loading I get this error:

```
TypeError: can't access property "requestAdapter", i[e] is undefined
```

And I have plenty of warnings of type

```
Warning: Token '<|29.90|>' was expected to have ID '51859' but was given ID 'None' [451-bef1ecb884dd18e5.js:2:958](https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js)
Warning: Token '<|29.92|>' was expected to have ID '51860' but was given ID 'None' [451-bef1ecb884dd18e5.js:2:958](https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js)
Warning: Token '<|29.94|>' was expected to have ID '51861' but was given ID 'None' [451-bef1ecb884dd18e5.js:2:958](https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js)
Warning: Token '<|29.96|>' was expected to have ID '51862' but was given ID 'None' [451-bef1ecb884dd18e5.js:2:958](https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js)
Warning: Token '<|29.98|>' was expected to have ID '51863' but was given ID 'None' [451-bef1ecb884dd18e5.js:2:958](https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js)
```

**Comment by FL33TW00D** [comment]
@maxime1992 I think FF support on Linux is rocky but have reached out to the team to double-check. Would recommend trying with a Chromium based browser for better support :)
