### ISSUE TITLE
[Question] Support Large Model

### ISSUE THREAD

**Issue by Mineru98** [FL33TW00D/whisper-turbo#31]
1. I don't think there is a binary file yet because the source code seems to support the Large model. Is it currently being built?
2. ~~As far as I know in openai, there are whisper large v2, are you planning to make large v2 as well?~~
Looking at [this link](https://huggingface.co/ggerganov/whisper.cpp), it's only possible up to v1.

**Comment by FL33TW00D** [comment]
> 1. I don't think there is a binary file yet because the source code seems to support the Large model. Is it currently being built?
> 2. ~As far as I know in openai, there are whisper large v2, are you planning to make large v2 as well?~
>    Looking at [this link](https://huggingface.co/ggerganov/whisper.cpp), it's only possible up to v1.

1. Large model is going to be feature gated for enterprise only. Once we fix some bugs and ship quantization Large-V2 will be available.
2. I've implemented the runtime myself, no whisper.cpp so any restrictions they have are N/A.

**Comment by Mineru98** [comment]
> > 1. I don't think there is a binary file yet because the source code seems to support the Large model. Is it currently being built?
> > 2. ~As far as I know in openai, there are whisper large v2, are you planning to make large v2 as well?~
> >    Looking at [this link](https://huggingface.co/ggerganov/whisper.cpp), it's only possible up to v1.
> 
> 1. Large model is going to be feature gated for enterprise only. Once we fix some bugs and ship quantization Large-V2 will be available.
> 2. I've implemented the runtime myself, no whisper.cpp so any restrictions they have are N/A.

1. Enterprise only is welcome. 😄 
2. That's good too 😄 
3. If the large model is improved, will you write a contact somewhere in the repository?

**Comment by FL33TW00D** [comment]
> > > 1. I don't think there is a binary file yet because the source code seems to support the Large model. Is it currently being built?
> > > 2. ~As far as I know in openai, there are whisper large v2, are you planning to make large v2 as well?~
> > >    Looking at [this link](https://huggingface.co/ggerganov/whisper.cpp), it's only possible up to v1.
> > 
> > 
> > 
> > 1. Large model is going to be feature gated for enterprise only. Once we fix some bugs and ship quantization Large-V2 will be available.
> > 2. I've implemented the runtime myself, no whisper.cpp so any restrictions they have are N/A.
> 
> 1. Enterprise only is welcome. 😄
> 2. That's good too 😄
> 3. If the large model is improved, will you write a contact somewhere in the repository?

I’ll keep this issue open until I am happy with the state of large-v2, and will let you know when it ships.

Current ETA is mid November

**Comment by FL33TW00D** [comment]
@Mineru98 Large-v2 is comfortably supported on v0.8.0 now, file size is 1.7GB zstd.
