### ISSUE TITLE
[BUG] whisper.rs:208:76: called `Result::unwrap()` on an `Err` value: BufferAsyncError(BufferAsyncError)

### ISSUE THREAD

**Issue by faveoled** [FL33TW00D/whisper-turbo#32]
Thanks for your work, very cool project.
I'm getting these errors in browser console (Chrome 117.0.5938.150 on Windows 10):
```
451-bef1ecb884dd18e5.js:1 panicked at /Users/fleetwood/Code/whisper-web/crates/whisper-core/src/whisper.rs:208:76:
called `Result::unwrap()` on an `Err` value: BufferAsyncError(BufferAsyncError)

Stack:

Error
    at t.wbg.__wbg_new_abda76e883ba8a5f (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:17432)
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2042]:0x2e752a
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2734]:0x2ff385
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2307]:0x2f3038
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[229]:0x7b44b
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[1244]:0x292720
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2947]:0x301b9f
    at m (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:13180)
    at _ (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:13056)
```
```
whisper-webgpu_bg.9e5117bc.wasm:0x2e7640 Uncaught (in promise) RuntimeError: unreachable
    at whisper-webgpu_bg.9e5117bc.wasm:0x2e7640
    at whisper-webgpu_bg.9e5117bc.wasm:0x2ff385
    at whisper-webgpu_bg.9e5117bc.wasm:0x2f3038
    at whisper-webgpu_bg.9e5117bc.wasm:0x7b44b
    at whisper-webgpu_bg.9e5117bc.wasm:0x292720
    at whisper-webgpu_bg.9e5117bc.wasm:0x301b9f
    at m (451-bef1ecb884dd18e5.js:1:13180)
    at _ (451-bef1ecb884dd18e5.js:1:13056)
```
Possibly because of these errors that look like Chrome ones:
```
ID3D12Device::GetDeviceRemovedReason failed with DXGI_ERROR_DEVICE_HUNG (0x887A0006)
 - While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
    at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:96)
    at CheckAndUpdateCompletedSerials (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:359)
    at CheckPassedSerials (..\..\third_party\dawn\src\dawn\native\ExecutionQueue.cpp:33)
    at Tick (..\..\third_party\dawn\src\dawn\native\Device.cpp:1325)

whisper-turbo.com/:1 ID3D12Device::GetDeviceRemovedReason failed with DXGI_ERROR_DEVICE_HUNG (0x887A0006)
 - While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
    at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:96)
    at CheckAndUpdateCompletedSerials (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:359)
    at CheckPassedSerials (..\..\third_party\dawn\src\dawn\native\ExecutionQueue.cpp:33)
    at Tick (..\..\third_party\dawn\src\dawn\native\Device.cpp:1325)
```
My main problem is not the error itself, but that I wasted some time because UI didn't tell me that some error happened and the spinner was spinning happily forever

**Comment by FL33TW00D** [comment]
> Thanks for your work, very cool project. I'm getting these errors in browser console (Chrome 117.0.5938.150 on Windows 10):
> 
> ```
> 451-bef1ecb884dd18e5.js:1 panicked at /Users/fleetwood/Code/whisper-web/crates/whisper-core/src/whisper.rs:208:76:
> called `Result::unwrap()` on an `Err` value: BufferAsyncError(BufferAsyncError)
> 
> Stack:
> 
> Error
>     at t.wbg.__wbg_new_abda76e883ba8a5f (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:17432)
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2042]:0x2e752a
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2734]:0x2ff385
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2307]:0x2f3038
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[229]:0x7b44b
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[1244]:0x292720
>     at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.9e5117bc.wasm:wasm-function[2947]:0x301b9f
>     at m (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:13180)
>     at _ (https://whisper-turbo.com/_next/static/chunks/451-bef1ecb884dd18e5.js:1:13056)
> ```
> 
> ```
> whisper-webgpu_bg.9e5117bc.wasm:0x2e7640 Uncaught (in promise) RuntimeError: unreachable
>     at whisper-webgpu_bg.9e5117bc.wasm:0x2e7640
>     at whisper-webgpu_bg.9e5117bc.wasm:0x2ff385
>     at whisper-webgpu_bg.9e5117bc.wasm:0x2f3038
>     at whisper-webgpu_bg.9e5117bc.wasm:0x7b44b
>     at whisper-webgpu_bg.9e5117bc.wasm:0x292720
>     at whisper-webgpu_bg.9e5117bc.wasm:0x301b9f
>     at m (451-bef1ecb884dd18e5.js:1:13180)
>     at _ (451-bef1ecb884dd18e5.js:1:13056)
> ```
> 
> Possibly because of these errors that look like Chrome ones:
> 
> ```
> ID3D12Device::GetDeviceRemovedReason failed with DXGI_ERROR_DEVICE_HUNG (0x887A0006)
>  - While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
>     at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:96)
>     at CheckAndUpdateCompletedSerials (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:359)
>     at CheckPassedSerials (..\..\third_party\dawn\src\dawn\native\ExecutionQueue.cpp:33)
>     at Tick (..\..\third_party\dawn\src\dawn\native\Device.cpp:1325)
> 
> whisper-turbo.com/:1 ID3D12Device::GetDeviceRemovedReason failed with DXGI_ERROR_DEVICE_HUNG (0x887A0006)
>  - While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
>     at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:96)
>     at CheckAndUpdateCompletedSerials (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:359)
>     at CheckPassedSerials (..\..\third_party\dawn\src\dawn\native\ExecutionQueue.cpp:33)
>     at Tick (..\..\third_party\dawn\src\dawn\native\Device.cpp:1325)
> ```
> 
> My main problem is not the error itself, but that I wasted some time because UI didn't tell me that some error happened and the spinner was spinning happily forever

Yeah error feedback is rudimentary at the moment.
I've seen this error on a Windows VM with older drivers, but there could be many reasons for it.

You could try a smaller model or updating drivers?

**Comment by faveoled** [comment]
I used the smallest model. Windows didn't have any proposed updates. I thunk my GPU doesn't support DX 12 that's it
