### ISSUE TITLE
Some dependencies seems to be unnecessary

### ISSUE THREAD

**Issue by DavidGOrtega** [FL33TW00D/whisper-turbo#37]
- @ffmpeg/ffmpeg
 - @ffmpeg/uti
 - p-limit
 
Are they needed? ffmpeg forces you to use node >= 18

**Comment by FL33TW00D** [comment]
> * @ffmpeg/ffmpeg
> * @ffmpeg/uti
> * p-limit
> 
> Are they needed? ffmpeg forces you to use node >= 18

Ffmpeg is already removed just need to do another release.

p-limit is used, but it’s a simple lib I can replace. 

Appreciate you letting me know!

**Comment by FL33TW00D** [comment]
@DavidGOrtega are you sure p-limit causes a node18 requirement? Seems to be Node12

**Comment by DavidGOrtega** [comment]
> Are they needed? ffmpeg forces you to use node >= 18

@FL33TW00D I said ffmpeg, sorry if I did not explain myself properly. 



> p-limit is used, but it’s a simple lib I can replace.

I do not have nothing against it! but I was not able to find code using it 🙂

**Comment by DavidGOrtega** [comment]
> Ffmpeg is already removed just need to do another release.

Is done in a PR? master code [still has it](https://github.com/FL33TW00D/whisper-turbo/blob/e406cf363c2fc65ccca04407377a26fed7b59577/package.json#L30) as a dependency

**Comment by FL33TW00D** [comment]
Dropped in the next release, closing.
