### ISSUE TITLE
Can not define language for model. Model sometimes wrong about language.

### ISSUE THREAD

**Issue by obenjiro** [FL33TW00D/whisper-turbo#45]
**Describe the bug**
Thanks for your awesome work! I currently have an issue that sometimes whisper correctly detects language and sometimes not. Is there a way to force language, of force model to always translate. Right now it's a random mix of two languages.

**To Reproduce**
1. Go to playground, select small model. 
2. Try to speak any non English language.
3. Try two cases. Start with english word first (then use your second language). Start with your second language.

**Desktop (please complete the following information):**
-  Reproduces everywere

**Additional context**

**Comment by FL33TW00D** [comment]
> **Describe the bug** Thanks for your awesome work! I currently have an issue that sometimes whisper correctly detects language and sometimes not. Is there a way to force language, of force model to always translate. Right now it's a random mix of two languages.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to playground, select small model.
> 2. Try to speak any non English language.
> 3. Try two cases. Start with english word first (then use your second language). Start with your second language.
> 
> **Desktop (please complete the following information):**
> 
> * Reproduces everywere
> 
> **Additional context**

I think this is inherent to the model. Good comment here: https://github.com/openai/whisper/discussions/1456#discussioncomment-6319478

Basically even large-v2 is poor at selecting the correct language. I can surface the ability to hardcode the language though.

**Comment by obenjiro** [comment]
> Basically even large-v2 is poor at selecting the correct language. I can surface the ability to hardcode the language though.

That would be awesome. If there's anything I can do to help, I'd be happy to assist.

**Comment by FL33TW00D** [comment]
> > Basically even large-v2 is poor at selecting the correct language. I can surface the ability to hardcode the language though.
> 
> That would be awesome. If there's anything I can do to help, I'd be happy to assist.

A DecodingOptions struct much like the one in the original OAI repo will be made available in the release this week!

**Comment by FL33TW00D** [comment]
@obenjiro This is being released this week - would appreciate you testing it out!

**Comment by DavidGOrtega** [comment]
> @obenjiro This is being released this week - would appreciate you testing it out!

How do you specify it in the command line?

**Comment by DavidGOrtega** [comment]
Ratchet 🚀 

Im in if you open source it. I wrote a very simple one a few years ago to make my models as photoshop plugins access gpu using Google angle (WebGL).
 
I have followed wgpu inference frameworks like burn-rs and wonnx. 
Probably candle at some point and TVM soon as they have some efforts already done.

Are you releasing whisper-turbo with wgpu?

**Comment by FL33TW00D** [comment]
> Ratchet 🚀
> 
> Im in if you open source it. I wrote a very simple one a few years ago to make my models as photoshop plugins access gpu using Google angle (WebGL).
> 
> I have followed wgpu inference frameworks like burn-rs and wonnx. Probably candle at some point and TVM soon as they have some efforts already done.
> 
> Are you releasing whisper-turbo with wgpu?

I'll the Apache license to whisper-webgpu in the next release!

Yeah it's built on top of wgpu!

**Comment by FL33TW00D** [comment]
@obenjiro I am pretty confident this is fixed - please reraise if not.

Closing.
