### ISSUE TITLE
Integration examples

### ISSUE THREAD

**Issue by FL33TW00D** [FL33TW00D/whisper-turbo#46]
- [ ] Cloudflare workers
- [ ] React
- [ ] Electron
- [ ] Tauri

**Comment by DavidGOrtega** [comment]
@FL33TW00D can you please specify a bit more what do you need?

**Comment by FL33TW00D** [comment]
> @FL33TW00D can you please specify a bit more what do you need?

Hi David,
It would be great to have an `examples` folder using whisper-turbo in an electron app or similar.
Just something so people can get started with it.

The code for the playground isn't top notch, so some out of the box examples + the new docs would be great!

I'm releasing 0.10.0 tomorrow which should nail down the public API (it's the same as OpenAI [here](https://github.com/openai/whisper/blob/fcfeaf1b61994c071bba62da47d7846933576ac9/whisper/transcribe.py#L141)), the examples should be stable after that).

Appreciate you asking!

**Comment by DavidGOrtega** [comment]
> It would be great to have an examples folder using whisper-turbo in an electron app or similar.

I can do that. Another idea could be expose whisper-turbo via rest api accessing the WebGPU with electron. I have a project never released that do that with LLMs

**Comment by FL33TW00D** [comment]
> > It would be great to have an examples folder using whisper-turbo in an electron app or similar.
> 
> I can do that. Another idea could be expose whisper-turbo via rest api accessing the WebGPU with electron. I have a project never released that do that with LLMs

Awesome that sounds great!

**Comment by DavidGOrtega** [comment]
Im attacking this on fri. Sorry for the delay, so many things 😢

**Comment by DavidGOrtega** [comment]
Would you consider to have a monorepo having multiple packages? I think is more clean than having an examples folder

**Comment by FL33TW00D** [comment]
> Would you consider to have a monorepo having multiple packages? I think is more clean than having an examples folder

Good idea! No rush on implementing anything, still a fair few bugs in WT to work out!

**Comment by flatsiedatsie** [comment]
Just a vanilla JS example would also be great :-)

**Comment by FL33TW00D** [comment]
@flatsiedatsie You can check out examples on the updated version: https://github.com/FL33TW00D/ratchet/tree/master/examples/ratchet-whisper
