### ISSUE TITLE
[BUG] medium model will not output complete results

### ISSUE THREAD

**Issue by from-gu-wei** [FL33TW00D/whisper-turbo#53]
**Describe the bug**
- Medium model will not output complete results
  - The larger the model, the higher the probability of bug.
  - which occasionally happens in small one, etc.
  - Happens almost 99% when I use medium model for audio longer than 1 minute.
  - Occurs in most language audio.
  - I suspect there is some timeout or leakage.

**To Reproduce**
1. Select the medium model 
2. Select test.mp3
3. Setting the ’zh‘ language may reduce the chance of problems.
4. The console only shows the processing but does not return json.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome 119]
 - Also tried compiling locally

![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/1e333a93-bad0-41ca-86f7-8cffbd219003)
[test-audio.zip](https://github.com/FL33TW00D/whisper-turbo/files/13412783/test-audio.zip)

**Comment by FL33TW00D** [comment]
@from-gu-wei 

Thanks for the good bug report, most likely a Windows issue.

Will report back.

**Comment by FL33TW00D** [comment]
@from-gu-wei 
This is a symptom of the quantization, the network runs fine in FP32.

Will have to investigate deeper - apologies.

**Comment by from-gu-wei** [comment]
> @from-gu-wei
> 
> The problem here is:
> 
> * Quantized model gets caught in loops much easier
> * EOT token is never generated so segment is never sent back to the user.
> 
> Not sure there is more i can do here, the quantized model performs the best it can on lower resource languages. `large-v3` improves multilingual performance significantly and should be more resistant to quantization.
> 
> Please provide more sample audio if you think my reasoning is incorrect here.

I don't have enough knowledge to give effective advice.
In fact, I am a designer and only know a little basic development knowledge.
I can provide a lot of audio:
[test-audio-2.zip](https://github.com/FL33TW00D/whisper-turbo/files/13424161/test-audio-2.zip)

The ones below are too big and you need to monitor the network to download them:
[#173 雑談回 旅行で感じた住みやすい環境を話したら対照的だった](https://podcasts.apple.com/us/podcast/173-%E9%9B%91%E8%AB%87%E5%9B%9E-%E6%97%85%E8%A1%8C%E3%81%A7%E6%84%9F%E3%81%98%E3%81%9F%E4%BD%8F%E3%81%BF%E3%82%84%E3%81%99%E3%81%84%E7%92%B0%E5%A2%83%E3%82%92%E8%A9%B1%E3%81%97%E3%81%9F%E3%82%89%E5%AF%BE%E7%85%A7%E7%9A%84%E3%81%A0%E3%81%A3%E3%81%9F/id1444665909?i=1000621681336)
[Full Cycle Developers at Netflix, 미국 연봉 정보 levels.fyi](https://podcasts.apple.com/us/podcast/full-cycle-developers-at-netflix-%EB%AF%B8%EA%B5%AD-%EC%97%B0%EB%B4%89-%EC%A0%95%EB%B3%B4-levels-fyi/id1440414478?i=1000567858263)

![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/85ffb9f5-b79a-4264-b170-3e8210dd509e)
![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/d041b88d-9797-4b0c-b27d-13ec1ea99ae5)
![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/f900d28e-8dda-44db-bb4c-69804ce127f6)

- Setting the language tag may reduce the chance of problems.

![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/c3276bcf-ed0f-4c06-89b0-2522a95c3032)
![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/4e689f11-2088-4019-8b8d-67645685e41b)

**Comment by FL33TW00D** [comment]
@from-gu-wei 
Thank you for providing more audio and the detailed reports!

Whisper is pretty bad at automatically detecting the language, I would recomend always setting it.

Additionally, I would recommend providing the audio in WAV format only. You can convert it with the following command:

`ffmpeg -i yourmp3.mp3 -acodec pcm_s16le -ar 16000 -ac 1 yourwav.wav`

Please let me know if WAV converting helps.

**Comment by from-gu-wei** [comment]
@FL33TW00D 

No, WAV converting does not work.

![image](https://github.com/FL33TW00D/whisper-turbo/assets/11283300/ba256171-c4ab-41a0-9a5d-a813cfb7292f)

**Comment by FL33TW00D** [comment]
@from-gu-wei,

Thanks for bearing with me.

I've compared my implementation against the OAI implementation using your provided: 
[Full Cycle Developers at Netflix, 미국 연봉 정보 levels.fyi](https://podcasts.apple.com/us/podcast/full-cycle-developers-at-netflix-%EB%AF%B8%EA%B5%AD-%EC%97%B0%EB%B4%89-%EC%A0%95%EB%B3%B4-levels-fyi/id1440414478?i=1000567858263)

It seems the smaller models are simply bad at lower resource languages.
The transcript is terminated due to the model getting caught in a bad loop.

I can improve the handling of this, but unfortunately the quality of `zh` transcription will remain poor until I ship `large-v3` which should handle things much better.

Apologies for the inconvenience, I will keep the issue open as I add the 1 or 2 mitigations I can.

PS:
Can you please provide the sample that repeatedly outputs "!", this seems like a failure on my end.

**Comment by from-gu-wei** [comment]
@FL33TW00D 

Thanks for all your work, once it's perfect it will change the ecology of many products. I also want to try to develop a little product based on this.

---

For me personally
- It can give stable results, even if the quality is not good, it doesn't matter.
  - _By the way, is there any way to introduce VAD to solve the hallucination problem?_
- And large-v3 may improve quality, but is too heavy for the out-of-the-box web.
- In fact, I'm considering using the small model if it can be even smaller.

---

PS: About "!", what information do I need to provide, it can be reproduced stably on my mac.

**Comment by FL33TW00D** [comment]
> @FL33TW00D
> 
> Thanks for all your work, once it's perfect it will change the ecology of many products. I also want to try to develop a little product based on this.
> 
> For me personally
> 
> * It can give stable results, even if the quality is not good, it doesn't matter.
>   
>   * _By the way, is there any way to introduce VAD to solve the hallucination problem?_
> * And large-v3 may improve quality, but is too heavy for the out-of-the-box web.
> * In fact, I'm considering using the small model if it can be even smaller.
> 
> PS: About "!", what information do I need to provide, it can be reproduced stably on my mac. The previous case was the audio file I provided earlier

Stable results should be possible, the model will need to reject samples using `compression_ratio_threshold` which needs to be added to `DecodingOptions`: https://www.ratchet.sh/whisper-turbo#decoding-options

For the "!" case, please provide the audio file (It can be trimmed to a shorter length if it produces "!" from the start).

Thanks again,
Chris

**Comment by from-gu-wei** [comment]
@FL33TW00D 

Well, this is some issue with Arc Browser.
It works fine after I switch to Chrome on mac.

---

What I mean is that any audio, including the Japanese and Korean podcasts above, will be output "!"

**Comment by FL33TW00D** [comment]
@from-gu-wei OK interesting! I haven't tested with arc!

**Comment by FL33TW00D** [comment]
@from-gu-wei OK to close? I will put the mitigations on the roadmap!

**Comment by from-gu-wei** [comment]
@FL33TW00D 

Of course no problem, thanks for your work.
---
If I want to inquire about something about this project, am I still raising an issue? This is my first time participating in an open source project, and there are many things I don’t understand.

**Comment by FL33TW00D** [comment]
> @FL33TW00D
> 
> ## Of course no problem, thanks for your work.
> If I want to inquire about something about this project, am I still raising an issue? This is my first time participating in an open source project, and there are many things I don’t understand.

Yes please raise anything and everything! The project is still young.
