### ISSUE TITLE
[Feature Request]  Integration of word-level timestamps

### ISSUE THREAD

**Issue by GuuuWei** [FL33TW00D/whisper-turbo#55]
The "word timestamps" feature would allow users to control the playback progress of an audio player and edit audio segments at a word level. This would be incredibly useful for applications requiring precise editing and navigation within audio files, such as in transcription, language learning tools, or detailed audio analysis.

Whisper already provides word-level timestamps.
I am looking forward to any information regarding the potential inclusion of this feature in the roadmap for Whisper-turbo.

Thank you for your time and the incredible work on this project.

**Comment by FL33TW00D** [comment]
> The "word timestamps" feature would allow users to control the playback progress of an audio player and edit audio segments at a word level. This would be incredibly useful for applications requiring precise editing and navigation within audio files, such as in transcription, language learning tools, or detailed audio analysis.
> 
> Whisper already provides word-level timestamps. I am looking forward to any information regarding the potential inclusion of this feature in the roadmap for Whisper-turbo.
> 
> Thank you for your time and the incredible work on this project.

This is something I do want to ship and shouldn't be *too* much work.
I can't say that it will be soon though - now that whisper-turbo is stable I am implementing more models.

**Comment by jozefchutka** [comment]
+1 I would love this feature

**Comment by ckhicks** [comment]
+1 to this! Already such an incredible effort but this would really make it a no-brainer for Electron usage vs firing out to serverless platforms, etc. Thanks for your work!

**Comment by FL33TW00D** [comment]
@jozefchutka @from-gu-wei @ckhicks 
word-level timestamps will be coming to the fully open source version!
Track the progress here: https://github.com/FL33TW00D/ratchet

**Comment by FL33TW00D** [comment]
Closing, hopefully someone ports word-level timestamps to the new OSS impl. Should be straightforward but isn't my top priority right now. See `TimestampRules` for an example: https://github.com/FL33TW00D/ratchet/blob/master/crates/ratchet-models/src/whisper/logit_mutators/timestamp_rules.rs

**Comment by iSuslov** [comment]
@FL33TW00D maybe we can reopen and offer a bounty to the one who will implement this? I'm ready to chip in.

**Comment by FL33TW00D** [comment]
> @FL33TW00D maybe we can reopen and offer a bounty to the one who will implement this? I'm ready to chip in.

Hey @iSuslov,
All work has moved into this repo: https://github.com/FL33TW00D/ratchet
Implementing word level timestamps would be just translating the offical codebase into here: https://github.com/FL33TW00D/ratchet/tree/master/crates/ratchet-models/src/whisper
