### ISSUE TITLE
[BUG] Repetitive Inputs didn't match, copying from user input

### ISSUE THREAD

**Issue by DavidGOrtega** [FL33TW00D/whisper-turbo#57]
Latest release does console.error continuously with the message `Inputs didn't match, copying from user input` 

Just try any file at whisper-turbo.com

**Comment by FL33TW00D** [comment]
@DavidGOrtega 

That log snuck in during the last release as I was testing performance improvements. The whole logging story of `whisper-turbo` needs a rework. I'll keep this open until I resolve it in 0.11.0.

Many Thanks,
Chris

**Comment by FL33TW00D** [comment]
This is fixed and will be released in 0.11.0, closing!
