### ISSUE TITLE
[BUG] whisper-turbo.com throws errors

### ISSUE THREAD

**Issue by jozefchutka** [FL33TW00D/whisper-turbo#59]
I am testing https://whisper-turbo.com/ with the most recent chrome on mac M2 and transcirptions fails with base and tiny models on [tos.mp3.zip](https://github.com/FL33TW00D/whisper-turbo/files/13456376/tos.mp3.zip)

```
Uncaught (in promise) {__wbg_ptr: 58389056}
```

![Screenshot 2023-11-24 at 8 41 56](https://github.com/FL33TW00D/whisper-turbo/assets/750041/7800a1e3-e9cf-404d-88cb-561cd7105765)

**Comment by FL33TW00D** [comment]
> I am testing https://whisper-turbo.com/ with the most recent chrome on mac M2 and transcirptions fails with base and tiny models on [tos.mp3.zip](https://github.com/FL33TW00D/whisper-turbo/files/13456376/tos.mp3.zip)
> 
> ```
> Uncaught (in promise) {__wbg_ptr: 58389056}
> ```
> 
> ![Screenshot 2023-11-24 at 8 41 56](https://user-images.githubusercontent.com/750041/285391836-7800a1e3-e9cf-404d-88cb-561cd7105765.png)

Hi Jozef,
Seems like a strange unsupported encoding of the MP3.

Encoding it using ffmpeg to WAV with the following:
`ffmpeg -i tos.mp3 -acodec pcm_s16le -ar 16000 -ac 1 tos.wav`

Works fine on the site.

However this does highlight the poor error handling and subpar audio transcoding. Will review it before 0.11 goes out.

Thanks for raising,
Chris

**Comment by jozefchutka** [comment]
Thanks for the quick response, I have created a new wav using `ffmpeg ... -acodec pcm_s16le -ar 16000 -ac 1 tos.wav`

[tos.wav.zip](https://github.com/FL33TW00D/whisper-turbo/files/13456839/tos.wav.zip)

Now using base model, it hangs mid-way with a different error:

`462.98ecf0d3854ca5c4.js:2 panicked at crates/whisper-core/src/logit_mutators/timestamp_rules.rs:87:62:`

![Screenshot 2023-11-24 at 9 39 17](https://github.com/FL33TW00D/whisper-turbo/assets/750041/a6c1c75b-3020-4a57-a732-002f60caed2d)

**Comment by FL33TW00D** [comment]
> Thanks for the quick response, I have created a new wav using `ffmpeg ... -acodec pcm_s16le -ar 16000 -ac 1 tos.wav`
> 
> [tos.wav.zip](https://github.com/FL33TW00D/whisper-turbo/files/13456839/tos.wav.zip)
> 
> Now using base model, it hangs mid-way with a different error:
> 
> `462.98ecf0d3854ca5c4.js:2 panicked at crates/whisper-core/src/logit_mutators/timestamp_rules.rs:87:62:`
> 
> ![Screenshot 2023-11-24 at 9 39 17](https://user-images.githubusercontent.com/750041/285403124-a6c1c75b-3020-4a57-a732-002f60caed2d.png)

99% sure this is the same error raised [here](https://github.com/FL33TW00D/whisper-turbo/issues/56#issuecomment-1823731853).

This has already been fixed and will be released in 0.11.0!

Apologies for the inconvenience,
Chris

**Comment by jozefchutka** [comment]
Thank you

**Comment by FL33TW00D** [comment]
@jozefchutka Can confirm this is fixed in 0.11.0. Releasing in the next few days.

**Comment by FL33TW00D** [comment]
@jozefchutka Please test on the latest version.

**Comment by jozefchutka** [comment]
.wav seems fixed, thanks... The strange unsupported encoding of the MP3 still broken but its not a problem anymore as I can work with wav. keep closed

**Comment by FL33TW00D** [comment]
> .wav seems fixed, thanks... The strange unsupported encoding of the MP3 still broken but its not a problem anymore as I can work with wav. keep closed

Awesome! I want to redesign some of the audio transcoding so may be fixed in the future!

**Comment by jozefchutka** [comment]
Could you please better clarify in [doc](https://www.ratchet.sh/whisper-turbo) what is the optimal input for `raw_audio`. I see doc mentioning Uint8Array of PCM (.wav). Here, in thread, I can see pcm_s16le / 16000 / mono. If this is the sufficient setup (no transcription precision improvements with higher sampling or channels) for PCM please mention in doc. Also I wonder if .pcm could be used instead of .wav

In comparison transformers.js consumes pcm_f32le/16000/mono .pcm file

**Comment by FL33TW00D** [comment]
> Could you please better clarify in [doc](https://www.ratchet.sh/whisper-turbo) what is the optimal input for `raw_audio`. I see doc mentioning Uint8Array of PCM (.wav). Here, in thread, I can see pcm_s16le / 16000 / mono. If this is the sufficient setup (no transcription precision improvements with higher sampling or channels) for PCM please mention in doc. Also I wonder if .pcm could be used instead of .wav
> 
> In comparison transformers.js consumes pcm_f32le/16000/mono .pcm file

`pcm_s16le / 16000 / mono` is 100% the "one true format". This comes directly from [OAI](https://github.com/openai/whisper/blob/e58f28804528831904c3b6f2c0e473f346223433/whisper/audio.py#L45).

When you use raw_audio I simply bypass any transcoding, whatever bytes you pass in will be used in the model.

Will clarify better in the docs!

**Comment by jozefchutka** [comment]
`pcm_s16le / 16000 / mono` + `raw_audio bypass any transcoding` very important information. thank you
