### ISSUE TITLE
whisper-webgpu.js panicked

### ISSUE THREAD

**Issue by olivermontes** [FL33TW00D/whisper-turbo#6]
Error try use playground

example audio
[example-audio.wav.zip](https://github.com/FL33TW00D/whisper-turbo/files/12588761/example-audio.wav.zip)

```
whisper-webgpu.js:522 panicked at /Users/fleetwood/Code/whisper-web/crates/whisper-core/src/whisper.rs:211:24:
called `Result::unwrap()` on an `Err` value: TooWide

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (webpack-internal:///./node_modules/whisper-webgpu/whisper-webgpu.js:515:21)
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[1818]:0x266653
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[2455]:0x27cc55
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[2059]:0x2711aa
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[214]:0x50dc6
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[1112]:0x22eee8
    at http://localhost:3000/_next/static/media/whisper-webgpu_bg.572596d0.wasm:wasm-function[2648]:0x27efec
    at __wbg_adapter_28 (webpack-internal:///./node_modules/whisper-webgpu/whisper-webgpu.js:217:10)
    at real (webpack-internal:///./node_modules/whisper-webgpu/whisper-webgpu.js:202:20)
```

**Comment by FL33TW00D** [comment]
Expect many issues as of now - it's not ready for public consumption right now!

**Comment by gabrielstuff** [comment]
Same error here on a Apple M1 Pro. How can we help ?

**Comment by FL33TW00D** [comment]
> Same error here on a Apple M1 Pro. How can we help ?

The deployed version only supports samples <30s & 16bit 16khz WAV right now.
I see you've been contributing to `ffmpeg.wasm` recently, help with the transcoding layer would be much appreciated.

**Comment by FL33TW00D** [comment]
<img width="1439" alt="image" src="https://github.com/FL33TW00D/whisper-turbo/assets/45471420/1f3a37dd-8c21-4e25-a3d2-bfc59acdd2a2">
Fixed will release

**Comment by FL33TW00D** [comment]
> Same error here on a Apple M1 Pro. How can we help ?

@gabrielstuff This is now deployed, supported formats are now `mp3`, `mp4`, `wav` and `m4a`. Additionally longer samples are supported, but buggy.
