### ISSUE TITLE
[Feature request] Add kill() to whisper-webgpu API

### ISSUE THREAD

**Issue by Huguet57** [FL33TW00D/whisper-turbo#62]
The only way to use JS workers with whisper-webgpu seems to be this repository. I found whisper-webgpu failing some of the times when saving the "medium" .bin model in the DB.

I actually have all that infrastructure built for myself (when I was using whisper.cpp).

Therefore, I think a kill() method in whisper-webgpu (maybe using flags or whatever) could be very beneficial for the widespread usage of the API. This API looks like the next big thing, would be cool to ask features directly to it instead of this wrapper.

**Comment by FL33TW00D** [comment]
Hi @Huguet57,
`whisper-turbo` is currently in the process of being open sourced at: https://github.com/FL33TW00D/ratchet

If you can wait a few more weeks, we can add the `kill` feature to that repo which will be supported in the future.

**Comment by Huguet57** [comment]
I saw that... Didn't know if that was actually the open-sourcing of whisper. That's great! I am an absolute noob in Rust but I can test it with an actual product: [https://fesmelacta.cat/](https://fesmelacta.cat/).

So that's great!
