### ISSUE TITLE
[Feature request] Condition on previous text

### ISSUE THREAD

**Issue by Huguet57** [FL33TW00D/whisper-turbo#64]
Hi,
It's me again. It would be pretty cool to add the condition_on_previous_text flag to whisper-webgpu as in: 

https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/transcribe.py#L278

Setting it to "false" can greatly reduce the failure loop cases. In minority languages is pretty usual.

**Comment by Huguet57** [comment]
Basically what the flag does is deleting the prompt that passes through the windows.

**Comment by FL33TW00D** [comment]
@Huguet57 Unfortunately, we won't be adding any more features to `whisper-turbo` until `ratchet` reaches feature parity.

We are pretty close to running Whisper on the new OSS framework (see [PR here](https://github.com/FL33TW00D/ratchet/pull/70)).

Once we've done that, we intend to add all sampling methods from the original repo.

**Comment by Huguet57** [comment]
Works for me! Even better if OSS. If any help testing is needed, let me know

**Comment by FL33TW00D** [comment]
Should be a 2 second job here: https://github.com/FL33TW00D/ratchet/blob/master/crates/ratchet-models/src/whisper/transcribe.rs#L97
