### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by gnehs** [FL33TW00D/whisper-turbo#65]
![image](https://github.com/FL33TW00D/whisper-turbo/assets/16719720/3f67b096-4c80-4756-b2dc-1c53d8a9c548)
https://www.ratchet.sh/whisper-turbo

I found an extra 's' in the worked example in the documentation, and I intended to submit a pull request to fix this issue. However, I couldn't locate the source file of the documentation, so I'm raising an issue here.

**Comment by FL33TW00D** [comment]
Fixed! Thank you!
