### ISSUE TITLE
Whisper Large V3

### ISSUE THREAD

**Issue by arces** [FL33TW00D/whisper-turbo#66]
Is it possible to add the Large model as an option? 
https://huggingface.co/openai/whisper-large-v3

I see that large is shown in the source code, but when I use whisper-turbo.com the largest option I see is medium. 

Btw, this is the best and easiest site I have found to transcribe stuff so thank you for creating this in the first place and thank you for hosting it. I really appreciate it!

**Comment by FL33TW00D** [comment]
@arces All future development is occurring here: https://github.com/FL33TW00D/ratchet

You can use distil large v3 here: https://huggingface.co/spaces/FL33TW00D-HF/ratchet-whisper
