### ISSUE TITLE
Modal not loading

### ISSUE THREAD

**Issue by ppsirius** [FL33TW00D/whisper-turbo#8]
After choosing the model nothing happened just text Load appears. But after choosing audio file I got error "no model loaded".

**Comment by FL33TW00D** [comment]
> After choosing the model nothing happened just text Load appears. But after choosing audio file I got error "no model loaded".

Presume you're on Windows? Currently only MacOS + Chrome is functional.

**Comment by ppsirius** [comment]
I'm on MacOS and Chrome, after select model no request are send for downloading model.

**Comment by FL33TW00D** [comment]
> I'm on MacOS and Chrome, after select model no request are send for downloading model.

Gotta press Load! Should be a green loading bar.

Will make the fact Load is a button more clear.

**Comment by ppsirius** [comment]
A little ux missmatch ;) Could be auto load after choosing the model.

**Comment by ppsirius** [comment]
Is making some chunks for file?
After finishing transcription could have possibility to download all text because only last text is shown?
